version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/cloudflare-record"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/deploy-key"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/hetzner-instance"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/repo-environment"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/stackit-object-storage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/stackit-postgres-db"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/stackit-secrets-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/stackit-state-bucket"
    schedule:
      interval: "weekly"
