name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install terraform
        uses: digitalservicebund/setup-terraform@adfabd79951446bc3078797c9cce4511328a8573 # v1.1.2
      - name: Check format
        run: |
          npx --yes prettier --check .
          terraform fmt -recursive -check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_module: ["stackit-s3-bucket", "stackit-state-bucket"]
    steps:
      - uses: actions/checkout@v5
      - name: "Install Terraform CLI"
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: v1.13.3

      - name: "Terraform Init"
        run: terraform init
        working-directory: ${{ matrix.terraform_module }}

      - name: Terraform Test
        run: terraform test
        working-directory: ${{ matrix.terraform_module }}
